# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: s2/v1/s2.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "s2/v1/s2.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0es2/v1/s2.proto\x12\x05s2.v1"4\n\x0eStreamPosition\x12\x0f\n\x07seq_num\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c"b\n\x0c\x41ppendRecord\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1e\n\x07headers\x18\x02 \x03(\x0b\x32\r.s2.v1.Header\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x42\x0c\n\n_timestamp"\x8f\x01\n\x0b\x41ppendInput\x12$\n\x07records\x18\x01 \x03(\x0b\x32\x13.s2.v1.AppendRecord\x12\x1a\n\rmatch_seq_num\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x1a\n\rfencing_token\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x10\n\x0e_match_seq_numB\x10\n\x0e_fencing_token"z\n\tAppendAck\x12$\n\x05start\x18\x01 \x01(\x0b\x32\x15.s2.v1.StreamPosition\x12"\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x15.s2.v1.StreamPosition\x12#\n\x04tail\x18\x03 \x01(\x0b\x32\x15.s2.v1.StreamPosition"c\n\x0fSequencedRecord\x12\x0f\n\x07seq_num\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x1e\n\x07headers\x18\x03 \x03(\x0b\x32\r.s2.v1.Header\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c"g\n\tReadBatch\x12\'\n\x07records\x18\x01 \x03(\x0b\x32\x16.s2.v1.SequencedRecord\x12(\n\x04tail\x18\x02 \x01(\x0b\x32\x15.s2.v1.StreamPositionH\x00\x88\x01\x01\x42\x07\n\x05_tailB\t\n\x05s2.v1P\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "s2.v1.s2_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\005s2.v1P\001"
    _globals["_STREAMPOSITION"]._serialized_start = 25
    _globals["_STREAMPOSITION"]._serialized_end = 77
    _globals["_HEADER"]._serialized_start = 79
    _globals["_HEADER"]._serialized_end = 116
    _globals["_APPENDRECORD"]._serialized_start = 118
    _globals["_APPENDRECORD"]._serialized_end = 216
    _globals["_APPENDINPUT"]._serialized_start = 219
    _globals["_APPENDINPUT"]._serialized_end = 362
    _globals["_APPENDACK"]._serialized_start = 364
    _globals["_APPENDACK"]._serialized_end = 486
    _globals["_SEQUENCEDRECORD"]._serialized_start = 488
    _globals["_SEQUENCEDRECORD"]._serialized_end = 587
    _globals["_READBATCH"]._serialized_start = 589
    _globals["_READBATCH"]._serialized_end = 692
# @@protoc_insertion_point(module_scope)
